# Generated by Django 4.0.3 on 2022-03-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7, unique=True, verbose_name='Matricula')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha Creacion')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelo.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Coche',
                'verbose_name_plural': 'Coches',
                'ordering': ['matricula'],
            },
        ),
    ]
